version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/Algo

    steps:
      - checkout

      # Restore Gradle cache
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle

      # Run Gradle build
      - run:
          name: Gradle Build
          command: ./gradlew build --no-daemon

      - codecov/upload

      # Save Gradle cache
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}

      # Store test results for CircleCI test reporting
      - store_test_results:
          path: build/test-results

      # Store build artifacts for CircleCI artifact storage
      - store_artifacts:
          path: build/libs

workflows:
  version: 2
  build:
    jobs:
      - build